### PR TITLE
Refactoring pkg structure

### PR DESCRIPTION
**Pull request by rafaeljesus**
After collecting some feedback in go community and studying interested projects around github I realized that cron-srv could have a clear package separation like https://github.com/apex/apex does for example, so this Pull Request introduces:

✅  Refactor package structure
✅  Removes echo in favor of a tiny router library which satisfies http.Handler interface
✅  Make scheduler thread safe with lock/unlock 
✅  Add capability to be multicore
✅  Extract runner object with channel based API
✅  Add tests for api routes
✅  Add tests for scheduler
✅  Add open source license

### CODE REVIEW

**Comment by rafaeljesus** [comment]
@EmpregoLigado/cabras can you 👀

**Comment by rafaeljesus** [comment]
👿

**Comment by efreesen** [comment]
Sorry, I am not having time to check this lately 😞

**Comment by rafaeljesus** [comment]
I totally understand mate @efreesen

**Review by aalvesjr — APPROVED** [review]
👏

**Comment by rafaeljesus** [comment]
@aalvesjr thx for reviewing, as this PR has some improvements I will only merge only after @hernandesbsousa and @efreesen review 👍

**Pull request merged**
